version: "3.8"
services:
  front:
    build:
      context: ./front
    ports:
      - "3000:3000"
    container_name: frontend
      
  back:
    build:
      context: ./back
    ports:
      - "8000:8000"
    container_name: backend